const RAW_STICKERS = [
  "photobooth/Sticker/Metalic/Metalic_0021_레이어-15.png",
  "photobooth/Sticker/Metalic/Metalic_0033_레이어-3.png",
  "photobooth/Sticker/Metalic/Metalic_0027_레이어-7.png",
  "photobooth/Sticker/Metalic/Metalic_0022_레이어-12.png",
  "photobooth/Sticker/Metalic/Metalic_0000_레이어-31-복사.png",
  "photobooth/Sticker/Metalic/Metalic_0034_레이어-0.png",
  "photobooth/Sticker/Metalic/Metalic_0018_레이어-16.png",
  "photobooth/Sticker/Metalic/Metalic_0032_레이어-2.png",
  "photobooth/Sticker/Metalic/Metalic_0025_레이어-10.png",
  "photobooth/Sticker/Metalic/Metalic_0024_레이어-9.png",
  "photobooth/Sticker/Metalic/Metalic_0026_레이어-6.png",
  "photobooth/Sticker/Metalic/Metalic_0014_레이어-19.png",
  "photobooth/Sticker/Metalic/Metalic_0013_레이어-21.png",
  "photobooth/Sticker/Metalic/Metalic_0009_kangjinju_Thorns_illuminated_by_blue_light._--ar_32_--profile_59f620ba-cc30-49f0-a137-23dc5cbdca2d_0.png",
  "photobooth/Sticker/Metalic/Metalic_0007_레이어-25.png",
  "photobooth/Sticker/Metalic/Metalic_0028_레이어-8.png",
  "photobooth/Sticker/Metalic/Metalic_0004_레이어-27.png",
  "photobooth/Sticker/Metalic/Metalic_0010_레이어-23.png",
  "photobooth/Sticker/Metalic/Metalic_0012_레이어-28.png",
  "photobooth/Sticker/Metalic/Metalic_0016_레이어-18.png",
  "photobooth/Sticker/Metalic/Metalic_0015_레이어-20.png",
  "photobooth/Sticker/Metalic/Metalic_0001_레이어-31.png",
  "photobooth/Sticker/Metalic/Metalic_0017_레이어-17.png",
  "photobooth/Sticker/Metalic/Metalic_0005_레이어-26.png",
  "photobooth/Sticker/Metalic/Metalic_0011_레이어-22.png",
  "photobooth/Sticker/Metalic/Metalic_0003_레이어-29.png",
  "photobooth/Sticker/Metalic/Metalic_0002_레이어-30.png",
  "photobooth/Sticker/Metalic/Metalic_0029_레이어-4.png",
  "photobooth/Sticker/Metalic/Metalic_0019_레이어-13.png",
  "photobooth/Sticker/Metalic/Metalic_0008_레이어-24.png",
  "photobooth/Sticker/Metalic/Metalic_0006_kangjinju_A_crown_surrounded_by_thin_thorns_illuminated_by_bl_eee81afa-c925-40ce-84b6-d3020cbd90cf_1.png",
  "photobooth/Sticker/Metalic/Metalic_0030_레이어-5.png",
  "photobooth/Sticker/Metalic/Metalic_0023_레이어-11.png",
  "photobooth/Sticker/Metalic/Metalic_0020_레이어-14.png",
  "photobooth/Sticker/Metalic/Metalic_0031_레이어-1.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0010_U.png",
  "photobooth/Sticker/Minimal/Minimal_0019_레이어-1.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0005_X.png",
  "photobooth/Sticker/Minimal/Minimal_0018_레이어-5.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0012_T.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0014_E.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0021_H.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0018_L.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0016_!.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0001_N.png",
  "photobooth/Sticker/Minimal/Minimal_0000_레이어-25.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0017_Q.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0019_K.png",
  "photobooth/Sticker/Minimal/Minimal_0003_레이어-22.png",
  "photobooth/Sticker/Minimal/Minimal_0022_레이어-4.png",
  "photobooth/Sticker/Minimal/Minimal_0016_레이어-8.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0006_Z.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0020_J.png",
  "photobooth/Sticker/Minimal/Minimal_0011_레이어-14.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0013_R.png",
  "photobooth/Sticker/Minimal/Minimal_0025_레이어-0.png",
  "photobooth/Sticker/Minimal/Minimal_0023_레이어-7.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0015_W.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0000_M.png",
  "photobooth/Sticker/Minimal/Minimal_0004_레이어-21.png",
  "photobooth/Sticker/Minimal/Minimal_0012_레이어-13.png",
  "photobooth/Sticker/Minimal/Minimal_0010_레이어-15.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0022_G.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0002_B.png",
  "photobooth/Sticker/Minimal/Minimal_0020_레이어-2.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0026_A.png",
  "photobooth/Sticker/Minimal/Minimal_0015_레이어-9.png",
  "photobooth/Sticker/Minimal/Minimal_0005_레이어-20.png",
  "photobooth/Sticker/Minimal/Minimal_0007_레이어-17.png",
  "photobooth/Sticker/Minimal/Minimal_0013_레이어-12.png",
  "photobooth/Sticker/Minimal/Minimal_0017_레이어-6.png",
  "photobooth/Sticker/Minimal/Minimal_0006_레이어-19.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0008_O.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0011_Y.png",
  "photobooth/Sticker/Minimal/Minimal_0001_레이어-24.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0004_C.png",
  "photobooth/Sticker/Minimal/Minimal_0002_레이어-23.png",
  "photobooth/Sticker/Minimal/Minimal_0021_레이어-3.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0024_D.png",
  "photobooth/Sticker/Minimal/Minimal_0014_레이어-11.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0003_V.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0009_I.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0007_P.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0023_F.png",
  "photobooth/Sticker/Minimal/Minimal_0008_레이어-18.png",
  "photobooth/Sticker/Minimal/Minimal_0009_레이어-16.png",
  "photobooth/Sticker/Minimal/Minimal_0000s_0025_S.png",
  "photobooth/Sticker/Minimal/Minimal_0024_레이어-10.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0022_레이어-13.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0029_레이어-5.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0018_레이어-17.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0032_레이어-11.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0028_레이어-4.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0009_레이어-25.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0021_레이어-12.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0003_레이어-30.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0013_레이어-21.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0010_레이어-24.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0006_레이어-28.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0007_레이어-27.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0031_레이어-11-복사.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0024_레이어-7.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0000_레이어-32.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0014_레이어-20.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0023_레이어-9.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0004_레이어-29.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0035_레이어-0.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0026_레이어-6.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0011_레이어-23.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0001_레이어-33.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0016_레이어-19.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0017_레이어-16.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0027_레이어-3.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0002_레이어-31.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0033_레이어-1.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0025_레이어-8.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0015_레이어-18.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0034_레이어-2.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0012_레이어-22.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0005_kangjinju_cupid_arrow._--ar_32_--profile_3wansvx_--v_7_399453da-57d3-4f31-8cf0-5325f353ba76_3.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0008_레이어-26.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0030_레이어-10.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0019_레이어-15.png",
  "photobooth/Sticker/Weird & Dreamy/Weird-&-Dreamy_0020_레이어-12-복사.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0035_레이어-6.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0025_레이어-14.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0037_레이어-8.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0032_레이어-4.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0019_레이어-19.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0020_레이어-20.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0009_레이어-30.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0026_레이어-15.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0034_레이어-5.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0015_레이어-29.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0017_레이어-23.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0000_레이어-37.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0004_레이어-36.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0010_레이어-31.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0007_레이어-34.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0028_레이어-12.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0002_레이어-38.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0013_레이어-27.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0016_레이어-24.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0001_레이어-38-복사.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0029_레이어-1.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0003_레이어-39.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0038_레이어-9.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0012_레이어-26.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0005_레이어-32.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0006_레이어-33.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0014_레이어-28.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0039_레이어-10.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0011_레이어-25.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0036_레이어-7.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0021_레이어-21.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0023_레이어-16.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0022_레이어-18.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0041_레이어-0.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0018_레이어-22.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0030_레이어-2.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0008_레이어-35.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0033_레이어-5-복사.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0027_레이어-13.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0024_레이어-17.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0040_레이어-11.png",
  "photobooth/Sticker/Kitch & Girlish/Kitch-&-Girlish_0031_레이어-3.png",
];
